### ISSUE TITLE
Unable to convert yolov4 onnx file

### ISSUE THREAD

**Issue by sharoseali** [ToriML/onnx2pytorch#13]
`python onnxtoPytorch.py
Traceback (most recent call last):
  File "onnxtoPytorch.py", line 5, in <module>
    pytorch_model = ConvertModel(onnx_model)
  File "/home/sharoze/.local/lib/python3.8/site-packages/onnx2pytorch/convert/model.py", line 63, in __init__
    for op_id, op_name, op in convert_operations(onnx_model, batch_dim):
  File "/home/sharoze/.local/lib/python3.8/site-packages/onnx2pytorch/convert/operations.py", line 182, in convert_operations
    raise NotImplementedError(
NotImplementedError: Conversion not implemented for op_type=Softplus.`

**Comment by Talmaj** [comment]
Resolved.
