### ISSUE TITLE
how can I infer converted model 

### ISSUE THREAD

**Issue by phamthanhdat270198** [ToriML/onnx2pytorch#18]

**Comment by phamthanhdat270198** [comment]
![image](https://user-images.githubusercontent.com/51939935/129475591-a50e1d12-48d5-4e53-8a45-0471245674b2.png)

**Comment by LukasStruppek** [comment]
Hey, which PyTorch version are you using? I also had problems with torch.clamp, but the functionality is changed in later versions. Maybe you could try PyTorch 1.9.0.

**Comment by londumas** [comment]
I can reproduce this bug, here is a minimal example:

```
import os
import onnx
import torch
import onnx2pytorch
import onnxruntime
import numpy as np

print("os",os.__file__)
print("onnx",onnx.__version__)
print("onnxruntime",onnxruntime.__version__)
#print(onnx2pytorch.__version__)
print("torch",torch.__version__)
print("numpy",np.__version__)

# wget https://github.com/onnx/models/raw/master/vision/classification/mobilenet/model/mobilenetv2-7.onnx

path_to_onnx_model = "<path to the model.onnx>"

###
onnxruntime_model = onnxruntime.InferenceSession(path_to_onnx_model)
inputs = [ el.shape for el in onnxruntime_model.get_inputs() ]
for i in range(len(inputs)):
    for j in range(len(inputs[i])):
        if type(inputs[i][j])==str:
            inputs[i][j] = 1
print(inputs)
t = np.random.rand(*inputs[0]).astype(np.float32)
ort_inputs = { onnxruntime_model.get_inputs()[0].name: t }
y = onnxruntime_model.run(None, ort_inputs)
print(y[0].shape)

###
onnx_model = onnx.load(path_to_onnx_model)
pytorch_model = onnx2pytorch.ConvertModel(onnx_model)
t = torch.Tensor(t)
y = pytorch_model(t)            
```

````
os <...>/lib/python3.9/os.py
onnx 1.10.2
onnxruntime 1.9.0
torch 1.9.1+cu102
numpy 1.19.5
[[1, 3, 224, 224]]
(1, 1000)
<...>/lib/python3.9/site-packages/onnx2pytorch/convert/layer.py:30: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  layer.weight.data = torch.from_numpy(numpy_helper.to_array(weight))
Traceback (most recent call last):
  File "exemple-bug.py", line 36, in <module>
    y = pytorch_model(t)
  File "<...>/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "<...>/lib/python3.9/site-packages/onnx2pytorch/convert/model.py", line 224, in forward
    activations[out_op_id] = op(*in_activations)
  File "<...>/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: torch.clamp: At least one of 'min' or 'max' must not be None

```

**Comment by carry-xz** [comment]
same problem， need better sample code about inference
