### ISSUE TITLE
cannot import name '_LazyBatchNorm' from 'torch.nn.modules.batchnorm'

### ISSUE THREAD

**Issue by londumas** [ToriML/onnx2pytorch#25]
code is broken on latest torch 1.10.0

```
>>> import torch
>>> torch.__version__
'1.10.0+cu102'
>>> import onnx2pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>/lib/python3.9/site-packages/onnx2pytorch/__init__.py", line 1, in <module>
    from .convert import ConvertModel
  File "<...>/lib/python3.9/site-packages/onnx2pytorch/convert/__init__.py", line 1, in <module>
    from .model import ConvertModel
  File "<...>/lib/python3.9/site-packages/onnx2pytorch/convert/model.py", line 14, in <module>
    from onnx2pytorch.constants import (
  File "<...>/lib/python3.9/site-packages/onnx2pytorch/constants.py", line 4, in <module>
    from onnx2pytorch.operations import (
  File "<...>/lib/python3.9/site-packages/onnx2pytorch/operations/__init__.py", line 2, in <module>
    from .batchnorm import BatchNormWrapper
  File "<...>/lib/python3.9/site-packages/onnx2pytorch/operations/batchnorm.py", line 4, in <module>
    from torch.nn.modules.batchnorm import _BatchNorm, _LazyBatchNorm
ImportError: cannot import name '_LazyBatchNorm' from 'torch.nn.modules.batchnorm' (<...>/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py)

```

**Comment by calvinmccarter-at-lightmatter** [comment]
Use the code from this PR: https://github.com/ToriML/onnx2pytorch/pull/23

**Comment by Talmaj** [comment]
Fixed in new version 0.4.1

**Comment by j29scott** [comment]
I installed the tool off pip a few minutes ago and observed this issue

**Comment by calvinmccarter-at-lightmatter** [comment]
@j29scott - can you double check your torch and onnx2pytorch versions? what are they?
